- name: Workspace settings | Nomes (4)
  become_user: victor
  xfconf:
    channel: xfwm4
    property: /general/workspace_names
    value_type: string
    value: ['1a', '2b', '3c', '4d']
      
- name: Workspace settings | Formato botões
  become_user: victor
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-4/miniature-view
    value_type: bool
    value: false

- name: Workspace settings | Botão de aplicações sem título
  become_user: victor
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-1/show-button-tittle
    value_type: bool
    value: false

- name: XFCE Panel | restart
  become: true
  become_user: victor
  command: 
    cmd: xfce4-panel --restart
